### ISSUE TITLE
Add extension- or plug-in mechanism to register new installer types

### ISSUE THREAD

**Issue by pschulz** [composer/installers#153]
It would be nice to write additional (may be proprietary) installers, that can reuse the existing functionality of this project.
Wouldn't it be nice to add installers just by writing a new class that extends the BaseInstaller and defines the $locations array without the need to modify Composer\Installers\Installer::$supported types?

**Comment by kwhat** [comment]
@davidbarratt the custom installer is exactly what I needed to accomplish the same thing.  Thanks for the tip.
