### ISSUE TITLE
Prefix vendor-dir if defined in user's composer.json to paths

### ISSUE THREAD

**Issue by shama** [composer/installers#164]
Ref #148.

Given the following `composer.json`:

``` json
{
    "repositories": [
        { "type": "git", "url": "https://github.com/Mihailoff/installer-test.git" }
    ],
    "require": {
        "mihailoff/installer-test": "0.1.0"
    },
    "config": {
        "vendor-dir": "custom"
    }
}
```

`installer-test` should be installed into `custom/blocks/installer-test` but currently it is installed into `blocks/installer-test`.

**Comment by slbmeh** [comment]
I don't think the default behavior should be to prefix when `vendor-dir` is set.  Given a scenario where you have installer supported packages and traditional libraries, but you want to rename the folder for the libraries... e.g. `"vendor-dir": ".vendor"`.

Instead, I believe it would be ideal to support `{$vendor-dir}` in the template transforms for the installer paths.

**Comment by alcohol** [comment]
Closing due to quiet period. Please re-open if still applicable.
