### ISSUE TITLE
Drupal Site

### ISSUE THREAD

**Issue by davidbarratt** [composer/installers#178]
In a [Drupal Multi-Site environment](https://www.drupal.org/documentation/install/multi-site). It would be really helpful if Composer Installers supported installing a Drupal Site. This would allow site administrators to manage each site in a different repository like [davidbarratt/davidwbarratt](https://github.com/davidbarratt/davidwbarratt). This would allow the admin to have each site separate from the Drupal install itself and use Composer to manage the sites across different environments (staging, dev, local, etc.).

It would also allow the site itself to define PHP/Drupal dependencies. (i.e. the site can list out all of the libraries, modules, themes, etc. that the site requires to operate). You could even use this in a single-site setup by just pointing the site to the "default" folder.

Not only would this be helpful to Drupal admins, it's a minimal change for Composer Installers.

Thanks!

**Comment by alcohol** [comment]
Closing due to quiet period. Please re-open if still applicable.
