### ISSUE TITLE
Composer not installing some packages when "extra" is set

### ISSUE THREAD

**Issue by gizburdt** [composer/installers#202]
I have a working composer.json file. I would like to install all my plugins/themes in "/content" and not in "/wp-content". That's why I added the following to my composer.json file:

```
"extra": {
    "installer-paths": {
         "content/plugins": ["type:wordpress-plugin"],
         "content/themes": ["type:wordpress-theme"]
    }
},
```

But when I add this, the packages with type wordpress-plugin and wordpress-plugin will not be installed. I can see the repositories all still loaded with `--verbose`

**Comment by danielneis** [comment]
Hello,

you may be missing the {$name}, {$vendor}, {$type} placeholders.
Try something like this:

"extra": {
    "installer-paths": {
         "content/plugins/{$name}/": ["type:wordpress-plugin"],
         "content/themes{$name}/": ["type:wordpress-theme"]
    }
},

**Comment by gizburdt** [comment]
That was the solution, I already found it a few days after I posted this. Thanks for your help ;)
