### ISSUE TITLE
Kindly explain the magic behind composer/installers

### ISSUE THREAD

**Issue by ADmad** [composer/installers#210]
Composer's [customer installers](https://getcomposer.org/doc/articles/custom-installers.md) doc states:

> A Custom Installer is defined as a class that implements the `Composer\Installer\InstallerInterface` and is usually distributed in a Composer Plugin 

But `Composer\InstallersBase\BaseInstaller` does not implement `Composer\Installer\InstallerInterface`. So what's magic behind it's working? Does composer check for this installer and give it special treatment?

**Comment by shama** [comment]
The magic is in [Installer.php](https://github.com/composer/installers/blob/master/src/Composer/Installers/Installer.php#L8) which extends `LibraryInstaller` as per https://getcomposer.org/doc/articles/custom-installers.md#the-custom-installer-class

`LibraryInstaller` implements `InstallerInterface`: https://github.com/composer/composer/blob/master/src/Composer/Installer/LibraryInstaller.php

**Comment by ADmad** [comment]
Thanks @shama. I should have checked better :)
