### ISSUE TITLE
How to deal with multiple installers registered for same package type

### ISSUE THREAD

**Issue by ADmad** [composer/installers#211]
Existing CakePHP 2.x plugins use `composer/installers` with type `cakephp-plugin`. For CakePHP 3.0 we  created our own installer [cakephp/plugin-installer](https://github.com/cakephp/plugin-installer) which also uses type `cakephp-plugin`. 

Now this creates an problem if in a CakePHP 3.0 app someone uses packages which uses `composer/installer` are reported here cakephp/plugin-installer#18. Probably depending on the order in which the installers are executed `composer/installer` takes over and installs the plugin instead of `cakephp/plugin-installer`.

To deal with this problem the apparent fix is to have `Composer\Installers\Installer::supports()` to return false for CakePHP 3.0 plugins. But way the code is structured it cannot be achieve by modifying the `CakePHPInstaller` class. Adding framework (type) specific code in `Composer\Installers\Installer` is far from ideal so can you provide suggestions how to deal with problem.

**Comment by shama** [comment]
I don't mind framework specific code in `Installer` if it means adding another framework to the natively supported list :)

I'll worry about a more elegant way down the road if more frameworks starting adopting their own installers.

**Comment by ADmad** [comment]
The solution now is to simply disable the CakePHP specific installer in CakePHP 3+ apps, by adding this to your composer.json:
```
{
    "extra": {
        "installer-disable": [
            "cakephp"
        ]
    }
}
```
