### ISSUE TITLE
Moodle plugins types not working correctly

### ISSUE THREAD

**Issue by danielneis** [composer/installers#214]
Hello,

i am having some problems with installing Moodle Plugins with the composer-installers.
As noted here (https://github.com/danielneis/moodle-block_attendance/blob/master/composer.json), moodle should be supported by installer, although this page (https://composer.github.io/installers/) does not list Moodle as an option.

I am trying to add a package,  to the "blocks" folder, but it is being added to vendor instead, as the type was not recognized.

I am using the following composer.json (https://github.com/danielneis/moodle-block_attendance/blob/master/composer.json) for the package:

    {
        "name": "danmarsden/moodle-block_attendance",
        "type": "moodle-block",
        "require": {
            "composer/installers": "~1.0"
        },
        "extra": {
            "installer-name": "attendance"
        }
    }

And here is the composer.json I am using on moodle root folder (the require-dev was already there and also the first repository):

    {
        "repositories" : [
            {
                "type": "vcs",
                "url": "https://github.com/moodlehq/moodle-behat-extension"
            },
            {
                "type":"package",
                "package":{
                    "version":"dev-master",
                    "name":"danmarsden/moodle-block_attendance",
                    "source":{
                        "url":"https://github.com/danielneis/moodle-block_attendance.git",
                        "type":"git",
                        "reference":"master"
                    },
                    "dist":{
                        "url":"https://github.com/danielneis/moodle-block_attendance/archive/master.zip",
                        "type":"zip"
                    }
                }
            }
        ],
        "require": {
            "danmarsden/moodle-block_attendance":"dev-master"
        },
        "require-dev": {
            "phpunit/phpunit": "3.7.*",
            "phpunit/dbUnit": "1.2.*",
            "moodlehq/behat-extension": "1.28.7"
        }
    }

It clones the correct repository from github but it is done on vendors/ directory instead of blocks/ as it should.

Am I missing something?

Kind regards,
Daniel

**Comment by shama** [comment]
@Mihailoff or @forloops would you mind helping out here?

**Comment by forloops** [comment]
@danielneis, you forgot the most important part, you need to require composer/installers in your require section. At the minimum in your moodle root, you need:
```
{
    "repositories" : [
        { "type": "vcs", "url":  "git@github.com:danielneis/moodle-block_attendance.git" }
    ],
    "require" : {
        "composer/installers" : "dev-master",
		"danmarsden/moodle-block_attendance" : "dev-master"
    }
} 
```

**Comment by danielneis** [comment]
thank you @forloops ! I was sure i was forgetting something, i may have tried "composer-installers" instead of the correct ""composer/installers" and haven't seen.

thank you very much! =D

**Comment by shama** [comment]
Thanks @forloops!

**Comment by forloops** [comment]
my pleasure :)
