### ISSUE TITLE
Installer Paths not working

### ISSUE THREAD

**Issue by dasuchin** [composer/installers#228]
In my root composer.json I have 
`
"extra": {
        "installer-paths": {
            "/": ["PackageVendor/PackageName"]
        }
    }
`

and in my composer package I have `"composer/installers": "~1.0"` under require.

But when I run `composer install`, it's still installing it in the vendor directory.

Any ideas?

**Comment by dasuchin** [comment]
Looks like I got it to work by setting it to `.`.

Is there a way I can make it not overrwite my composer.json with the one that's in the package?

**Comment by shama** [comment]
`/` usually means the root of the file system where `.` is the relative path. I don't recommend installing a package to your project base path though. That is basically saying, my app and all the work I've done to it will be replaced by this dependency when I run `composer install` which I doubt you want.
