### ISSUE TITLE
Add suport for install, update and uninstall events to BaseInstaller

### ISSUE THREAD

**Issue by Brainshack** [composer/installers#229]
Hello,

in the current installers, it seems only be possible for me, to provide paths, to where the packages are being installed. Sometimes however, it might be necessary to do additional things, after the package has been installed.
Composer supports this with it's custom installers, since the InstallerInterface provides methods for install, update and delete.

Would it be possible to add these hooks to the BaeInstaller aswell?

**Comment by shama** [comment]
I think custom installers are better suited for those use cases.
