### ISSUE TITLE
Mis-match between "type" and extra/class" in composer.json

### ISSUE THREAD

**Issue by sprak3000** [composer/installers#232]
The recent merge of PR `TomasVotruba:patch-`" causes this error when trying to run a composer update for my CakePHP 2.0 project:

```
Updating dependencies (including require-dev)
  - Installing composer/installers (dev-master 316656d)
    Cloning 316656d40baba4d46ff60f9fc64c52e5ce6b4849

  [ErrorException]
  Argument 1 passed to Composer\Installer\LibraryInstaller::__construct() must implement interface Compose
  r\IO\IOInterface, none given, called in phar:///Users/luis/path/to/app/Plugin/Composer/
  Vendor/Composer/composer.phar/src/Composer/Plugin/PluginManager.php on line 250 and defined
```

From the [composer docs](https://getcomposer.org/doc/articles/plugins.md), if you use `"type": "composer-plugin"`, the class you specify in `"extra": "class"` must implement `Composer\Plugin\PluginInterface`. Currently, the class specified is `Composer\\Installers\\Installer` which has the signature `class Installer extends LibraryInstaller`.

**Comment by shama** [comment]
Hmm sorry, reverted the commit for now. I'll need a bit of help fixing this one if anyone is available.
