### ISSUE TITLE
Update (or remove) the gh-pages branch

### ISSUE THREAD

**Issue by potherca** [composer/installers#236]
The website (on the `gh-pages` branch), especially the list of available supported types, is two years behind the README in the `master` branch.

I would *strongly* advocate either updating or otherwise simply deleting the `gh-pages` branch.

**Comment by shama** [comment]
Thanks! Updated.

**Comment by potherca** [comment]
This may be a stupid idea, but if the `gh-pages` branch is only a Jekyll generated version of the README file, wouldn't it be easier to just automate the process of updating that branch?

It would 'only' require 3 steps:
- Convert the static html page to a Jekyll template
- Add [frontmatter](http://jekyllrb.com/docs/frontmatter/) to the README file so it gets used as index file:

         ---
         permalink: /
         ---
-  Add a step to the build script on Travis to push changes in the README file to the gh-pages branch. (Or just always push it. Meh.)

Thoughts?
