### ISSUE TITLE
composer install install wordpress plugins to vendor dir

### ISSUE THREAD

**Issue by jacobmaster** [composer/installers#240]
Trying to install wordpress plugins with composer and wpacakagist
during `composer update` everything works fine - plugins installed in `wp-content/plugins directory`
but when i use `composer install` later - plugins are installed again but into `vendor/wpackagist-plugin`

Am I forgot something?

**Comment by michaelbeil** [comment]
Hey @jacobmaster,

You might want to checkout https://roots.io/using-composer-with-wordpress regarding this.
