### ISSUE TITLE
Only cake-DebugKit is installed if composer.lock is present

### ISSUE THREAD

**Issue by bakroistvan** [composer/installers#243]
Hi

I created the following composer.json

```
{
    "name": "eb",

    "config": {
        "vendor-dir": "Vendor",
        "component-dir": "webroot/assets"
    },

    "require" :
    {
        "php": ">=5.3",
        "ext-imagick": "*",
        "cakephp/cakephp": "^2.6.2",
        "cakephp/debug_kit": "^2.2.5",
        "slywalker/boost_cake": "^1.0.6",
        "josegonzalez/cakephp-upload": "^1.2.0",
        "phpoffice/phpexcel": "1.8.1",
        "zeroclipboard/zeroclipboard": "2.2.0",
        "components/jquery": "^1.11.0",
        "components/bootstrap": "^3.0.0"
    },

    "require-dev" :
    {
        "anahkiasen/rocketeer": "^2.1",
        "jeroendesloovere/vcard": "1.1.*"
    }
}
```

if i run

```
composer install
rm -rf Vendor webroot Plugin 
composer install
```

I have only DebugKit in my Plugin folder.
I am starting to get know each other with composer... Is the problem with my machine only???

**Comment by slbmeh** [comment]
I'm able to reproduce it. Can't seem to track down the source of the issue.

**Comment by slbmeh** [comment]
@RobLoach looks like a return true is causing the issue on `RobLoach/component-installer`

https://github.com/RobLoach/component-installer/blob/master/src/ComponentInstaller/Installer.php#L58-59

Once it gets installed spitting out a `get_class($this)` on LibraryInstaller shows every subsequent package being handled by `ComponentInstaller`

**Comment by RobLoach** [comment]
@slbmeh This has been merged into `0.2.0`, would you mind running an update and another attempt? Thanks.

**Comment by bakroistvan** [comment]
Thanks all the help. I updated and it goes smoothly. :)

**Comment by sbuzonas** [comment]
Can this issue be closed?

**Comment by bakroistvan** [comment]
Yes thank you all
