### ISSUE TITLE
Question: What should I set the "installer-path" to to install a package in the root folder?

### ISSUE THREAD

**Issue by lewisgoddard** [composer/installers#249]
[eustasy/puff-db](https://github.com/eustasy/puff-db) expects to be installed by being copied to the root of a copy of [eustasy/puff-core](https://github.com/eustasy/puff-core). I'd like to be able to update the core more easily by having _db_ rely on _core_, but use a custom installation location to put it in the root folder. What should I set the "installer-path" to to install a package in the root folder? 

### Core composer.json
```
{
    "name": "eustasy/puff-core",
    "require": {
        "composer/installers": "~1.0"
    }
}
```

### DB composer.json
```
{
    "name": "eustasy/puff-db",
    "require": {
        "eustasy/puff-core": "*",
        "composer/installers": "~1.0"
    }
    "extra": {
        "installer-paths": {
            "your/custom/path/{$name}/": ["eustasy/puff-core"]
        }
    }
}
```

**Comment by slbmeh** [comment]
Installing in the root folder, or any shared folder, would be very bad. Whenever the package gets updated composer deletes the directory it is installed in.

Also, this project isn't intended to be an all purpose installer. The readme has a list of currently supported package types.

Your best bet is to make a [custom installer](https://getcomposer.org/doc/articles/custom-installers.md).  You'd be even better off if you could leverage autoloading to support composer natively.

**Comment by lewisgoddard** [comment]
After some more research yesterday, I was informed that updating does remove the contents of a folder. It seems composer is not a solution to my development problem.
