### ISSUE TITLE
Craft CMS plugin path ignored, placed in 'vendor' directory

### ISSUE THREAD

**Issue by iparr** [composer/installers#268]
I've trying to use pull in this plugin: https://github.com/iparr/vanillaforums

I'm expecting that when I `composer install` in my project that it will move the plugin into `craft/plugins/vanillaforums` but instead it simply creates a `vendor` folder as if I wasn't using installers at all.

My projects `composer.json` is as follows:

```
{
    "name": "iparr/scg-craft",
    "license": "private",
    "authors": [
        {
            "name": "Ian Parr"
        }
    ],
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "iparr/vanillaforums",
                "version": "1.0",
                "source": {
                    "url": "git@github.com:iparr/vanillaforums.git",
                    "type": "git",
                    "reference": "origin/master"
                }
            }
        }
    ],
    "require": {
        "composer/installers": "dev-master",
        "iparr/vanillaforums": "*"
    }
}
```

Any help is appreciated.

**Comment by slbmeh** [comment]
Because you are declaring a package repository, the composer.json is not scanned for metadata.  The `iparr/vanillaforums` package is declared as a `library` type and has no dependency on `composer/installers` with that current composer.json. You should use a VCS repository instead.

**Comment by iparr** [comment]
Thanks.

Closing this as I think it highlights my complete lack of understanding of the Composer system rather than any specific problem!
