### ISSUE TITLE
follow export-ignore in package .gitattributes

### ISSUE THREAD

**Issue by pryley** [composer/installers#274]
composer/installers should follow the .gitattributes rules in a package.

For example, when fetching a custom wordpress plugin, it should exclude the src folder (.sass files, etc.) as set in the .gitattributes file when cloning to the plugins folder.

**Comment by slbmeh** [comment]
The `.gitattributes` file has nothing to do with excluding files.  The `.gitignore` file does, and it occurs by default as core piece of git functionality.

**Comment by pryley** [comment]
Late coming back to this. The case scenario for this issue was specifically when using composer to maintain and install WordPress plugins (from http://wpackagist.org). The .gitattributes file is used to exclude files/dirs when archiving a project for distribution.

Since the purpose of `composer/installers` is to: _install the package to the correct location based on the specified package type_, when used with WordPress plugins, it is assumed that the installed package is _distribution_ ready.
