### ISSUE TITLE
require composer-plugin-api needs version update?

### ISSUE THREAD

**Issue by vrga** [composer/installers#280]
I've been getting the following message on some of composer updates recently:

```The "composer/installers" plugin requires composer-plugin-api 1.0.0, this *WILL* break in the future and it should be fixed ASAP (require ^1.0 for example).```

I notice that this is not something visible on packagist, so i assume its something provided directly by composer itself.

Is this even relevant at all?

**Comment by Seldaek** [comment]
Fixed in 1.0.23, sorry about that :)
