### ISSUE TITLE
Doesn't work on repositories of type "path"

### ISSUE THREAD

**Issue by dsdeiz** [composer/installers#282]
I think I might be missing something but this doesn't seem to work with repositories of type "path". Here's my `composer.json`:

```json
{
    "repositories": [
        {
            "type": "path",
            "url": "packages/my-package"
        }
    ],
    "require": {
        "my/package": "*",
        "composer/installers": "^1.0"
    },
    "extra": {
        "installer-paths": {
            "web/modules/{$name}/": ["my/package"]
        }
    }
}
```

The package's `composer.json` is simply this:

```json
{
    "name": "my/package",
    "version": "1.0.0"
}
```

What happens is that the package is still installed inside the "vendor" directory. If I specify the type in the package's `composer.json` e.g. `drupal-module`, then I get this error:

>   [InvalidArgumentException]
  $from (modules/package/) and $to (/private/tmp/test/packages/my-package)
  must be absolute paths.

**Comment by jadb** [comment]
Thanks for reporting this. I will try replicating in a test and pushing a fix soon.

**Comment by dsdeiz** [comment]
I guess this is related to #272.

**Comment by dzuelke** [comment]
The issue is the trailing slash in the installer path. If you remove it, it'll work. Can you confirm?

**Comment by dsdeiz** [comment]
It didn't seem so. I used this:

```json
{
    "repositories": [
        {
            "type": "path",
            "url": "packages/my-package"
        }
    ],
    "require": {
        "my/package": "*",
        "composer/installers": "^1.0"
    },
    "extra": {
        "installer-paths": {
            "web/modules/{$name}": ["my/package"]
        }
    }
}
```

It still installed the package inside `vendor/packages/my-package`. Here's a tree:

```
$ tree
.
├── composer.json
├── composer.lock
├── packages
│   └── my-package
│       ├── composer.json
│       └── test.txt
└── vendor
    ...
    └── my
        └── package -> ../../packages/my-package
    ...
```

**Comment by dzuelke** [comment]
Hmh. It works with "type:wordpress-theme" or similar for me. I wonder what the difference is.

**Comment by Seldaek** [comment]
Closed by https://github.com/composer/composer/pull/5164

**Comment by dsdeiz** [comment]
Sorry, I can't still get this to work. This is my `composer.json`:

```json
{
    "repositories": [
        {
            "type": "path",
            "url": "packages/my-package"
        }
    ],
    "require": {
        "my/package": "*",
        "composer/installers": "@dev",
        "composer/composer": "@dev"
    },
    "extra": {
        "installer-paths": {
            "some/path/{$name}": ["my/package"]
        }
    }
}
```

Ran `vendor/bin/composer` and still the path is stored inside `vendor/my/package` instead of `some/path/my-package`. Anything I'm missing?

**Comment by Seldaek** [comment]
If you could publish a small git repo with the composer.json of `my/package` and enough data in there that we can clone that, and install a composer.json somewhere else to try and reproduce it, that'd be great.

**Comment by dsdeiz** [comment]
I created a repo [here](https://github.com/dsdeiz/tmp-composer-installer). `my/package` isn't on another repository though but this is what I used to test. Hope this helps.

**Comment by dzuelke** [comment]
`installer-paths` is handled by composer/installers, and only for the types that supports, @dsdeiz. So you can't custom-map a generic Composer package type such as "library".

**Comment by dsdeiz** [comment]
Sweet, thanks! Yeah this works now. Been a while since I last used `composer/installers`. I also don't get this error anymore:

> [InvalidArgumentException]
$from (modules/package/) and $to (/private/tmp/test/packages/my-package)
must be absolute paths.

All good!
