### ISSUE TITLE
Install a subdirectory of a package to the installer-path

### ISSUE THREAD

**Issue by timkelty** [composer/installers#286]
I'm wondering if there is a way to install a package, where the contents that need to be installed to the `installer-path` actually is a subdirectory of the repo/package.

Example: https://github.com/johndwells/craft.minimee, is a `craft-plugin`. The author has the folder (`minimee/`) that needs to be moved to `craft/app/plugins/` actually in the repo. Other authors just put the contents of that folder in the root, but since the proper naming of that folder is crucial, it is easy to see why authors sometimes include it.

**Comment by roelvanhintum** [comment]
I'm running into this same problem with https://github.com/pixelandtonic/ElementAPI of all plugins.

**Comment by slbmeh** [comment]
This particular case is similar to the feature requested in composer/composer#3037.  There is a target-directory configuration, I don't believe anyone has ever suggested the inverse as a feature in `composer/composer`.

**Comment by timkelty** [comment]
@slbmeh Any guidance here would be great.

### Here's the use-case:
A number of plugin developers in the [Craft CMS](http://craftcms.com) community have adopted using `craft-plugin` from `composer/installers`, myself included. Great.

However, many people are opposed to the idea, simply because they don't want to restructure their repos to have the "plugin directory" at the root. Instead they have it in a appropriately named folder (e.g. https://github.com/pixelandtonic/ElementAPI).

This is understandable because the folder has to named correctly in the install path `craft/plugins/pluginName` to work correctly. To achieve this, `craft-plugin` relies on stripping `craft` and `plugin` from the repo name.

### What is the right course of action here?
- Is there an option these authors can use to tell `composer/installers` to use `./myPluginName` as the base path for installing? Would this be a `composer/composer` thing or `composer/installers`, or should there be?
- Should the `craft-plugin` functionality simply be changed use the subdirectory?
- Should there be a separate `craft-plugin-nested` for this? (seems dumb)

**Comment by alcohol** [comment]
Closing due to quiet period. Please re-open if still applicable.
