### ISSUE TITLE
Change DrupalInstaller locations to use contrib folder

### ISSUE THREAD

**Issue by edysmp** [composer/installers#293]
Example:
We need organize modules it using this http://cgit.drupalcode.org/drupal/tree/modules/README.txt?h=8.0.5#n16

```
    protected $locations = array(
        'core'      => 'core/',
        'module'    => 'modules/contrib/{$name}/',
        'theme'     => 'themes/contrib/{$name}/',
        'library'   => 'libraries/contrib/{$name}/',
        'profile'   => 'profiles/contrib/{$name}/',
    );
```

**Comment by slbmeh** [comment]
That links reads as if those directory names are examples being that is says _"may"_.  Additionally, as stated in PR #294, some of those types are marked stable and are expected to never change according to the readme for this project.

**Comment by FGM** [comment]
This is actually considered standard practice, much the same as using `sites/all/*/contrib` has been for years on Drupal 7. Most projects end up using a `contrib/` directory for contrib code, `custom/` (or `bespoke/`) for site-specific code, often splitting "features" modules to `custom/features/` or just `features/`.

**Comment by alcohol** [comment]
Closing due to quiet period. Please re-open if still applicable.

**Comment by FGM** [comment]
It doesn't really matter anyway, since it can be overridden in the extra/installer-paths section of the project composer.json, which is what drupal-composer/drupal-project does, like this:
```
  "extra": {
    "installer-paths": {
      "import": ["type:zend-extra"],
      "web/core": ["type:drupal-core"],
      "web/libraries/{$name}": ["type:drupal-library"],
      "web/modules/contrib/{$name}": ["type:drupal-module"],
      "web/profiles/contrib/{$name}": ["type:drupal-profile"],
      "web/themes/contrib/{$name}": ["type:drupal-theme"],
      "drush/contrib/{$name}": ["type:drupal-drush"]
    },
```
