### ISSUE TITLE
getInstallPath() returns only relative path

### ISSUE THREAD

**Issue by aimeos** [composer/installers#307]
There's an inconsistency to composer regarding getInstallPath():
Composer returns the absolute path while the composer installers only return the relative path:
https://github.com/composer/installers/blob/master/src/Composer/Installers/BaseInstaller.php#L36

Thus, this code fails because `symlink` links to a non-existing directory:

```
$repository = $event->getComposer()->getRepositoryManager();
$t3package = $repository->findPackage( 'aimeos/aimeos-typo3', '*' );
$package = $repository->findPackage( 'aimeos/ai-typo3', '*' );

$t3path = $installer->getInstallPath( $t3package );
$path = dirname( $installer->getInstallPath( $package ) );
symlink( $path, $t3path . '/Resources/Private/Extensions' );
```

$t3path is absolute as expected, but $path is relative (e.g. "ext" instead of "/path/to/ext")

**Comment by slbmeh** [comment]
What is the issue here?

**Comment by aimeos** [comment]
Like we've written: For packages in ./vendor/ composer returns an absolute path to packages, the installer returns only a relative path to the base directory when using getInstallPath()

**Comment by slbmeh** [comment]
Oh, I understand now. The example uses two packages with package types supported here, so in theory they should do the same thing sans the obvious path differences...
