### ISSUE TITLE
Untyped package not moved from vendor directory to custom path

### ISSUE THREAD

**Issue by iainhouston** [composer/installers#308]
My Github package is a directory of files of no pre-designated type. i.e. it is not a  `"type:drupal-theme"` or anything. This package's `composer.json` says:

```
  {
    "name": "iainhouston/pellucid_configuration",
    "description": "Drupal 8 configuration directory for pellucid_build",
    "extra": {
          "installer-name": "sync"
      },
    "license": "GPL-2.0+",
    "keywords": ["pellucid", "php"],
    "homepage": "https://iainhouston.com",
    "minimum-stability": "dev",
    "authors": [
      {
        "name": "Iain Houston",
        "email": "iainhouston@mac.com"
      }
    ],
    "require": { }
   }     
```

and the project's `composer.json` says:

```
"require": {
    "composer/installers": "^1.0.20",
...
},
...
"extra": {
    "installer-paths": {
     ...
      "web/sites/default/files/config/{$name}/": [  "iainhouston/pellucid_configuration"  ]
    }
```

   }

After I do `composer require iainhouston/pellucid_configuration`
the package is downloaded but remains in `vendor` and is not moved to `web/sites/default/files/config/sync/`

`web/sites/default/files/config/` exists and is writable by the user of composer.

BTW Other packages that I keep in GitHub are moved to to the correct "installer-paths" but these do have pre-designated types: `"type:drupal-module"` and `"type:drupal-theme"` and "type:drupal-library"

What am I doing wrong?

**Comment by slbmeh** [comment]
This project only supports package types named in the readme.  Dynamic types/paths are not supported. https://github.com/composer/installers#should-we-allow-dynamic-package-types-or-paths-no

**Comment by welly** [comment]
@sbuzonas, the readme also shows an example as below:

```
{
    "extra": {
        "installer-paths": {
            "your/custom/path/{$name}/": ["shama/ftp", "vendor/package"]
        }
    }
}
```

I am reading this as being able to use your own repo that isn't one of the supported package types.

**Comment by sbuzonas** [comment]
The text above those examples states:

> If you are consuming a package that uses the composer/installers you can override the install path with the following extra in your composer.json

Meaning, you have a dependency on a project that requires `composer/installers` and has a supported package type. This project only acts on a package that it supports. If you control the dependency, there isn't anything preventing you from declaring the wrong type to trick the installer, but that sounds wrong to me. YMMV

**Comment by alcohol** [comment]
Closing due to quiet period. Please re-open if still applicable.
