### ISSUE TITLE
autoload is not working 

### ISSUE THREAD

**Issue by sunel** [composer/installers#310]
After creating  a custom installer the files moves to the given dir but the auto load doesn't work anymore.

**Comment by camspiers** [comment]
Hey @sunel are you able to provide more information. I don't think there is enough information here to help you.

**Comment by sunel** [comment]
i have created a new installer that will move the package to custom location. The files are moved correctly , but once the package is moved the "autoload" config that is given is not considered any more.

**Comment by camspiers** [comment]
Are you able to provide the code of the new installer, and also provide what your expectation is (like the location of the code etc).

**Comment by sunel** [comment]
Check this links for files

https://gist.github.com/sunel/fb4551be185eddfa9c45be94168613c4

when i run using the given composer.json 

the package moves to the correct location as given in the 

root
    Modules
        Admin

But the autoload 

```json

"autoload-dev": {
    "psr-4": {
      "Modules\\Admin\\": "src/"
    }
  },

```

this doesn't work any more

**Comment by sunel** [comment]
@camspiers any updates on this
