### ISSUE TITLE
Use installer paths from dependency

### ISSUE THREAD

**Issue by acbramley** [composer/installers#327]
Apologies if this is already a feature, but I can't get it to work for me.

I have a bunch of sites that share common modules and libraries (drupal 8) and I'm creating a composer lib that all those sites can use to keep it easier to maintain patches etc across sites.

I'm having issues getting the installer paths to be inherited from the dependency though, or is this not supported by composer/installers?

I.e:

My root package:
```
{
    "name": "djr/site-vanilla",
    "description": "Project template for Drupal 8 projects with composer",
    "type": "project",
    "license": "GPL-2.0+",
    "config": {
        "discard-changes" : true
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "myrepo.com/djr_libs.git"
        },
        {
            "type": "composer",
            "url": "https://packagist.drupal-composer.org"
        }
    ],
    "require": {
        "djr/djr_libs": "dev-master",
        "composer/installers": "^1.2.0",
        "cweagans/composer-patches": "^1.5.0"
    },
    "extra": {
        "installer-paths": {},
        "patches": {},
        "enable-patching": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

And djr_libs composer file:
```
{
    "name": "djr/djr_libs",
    "description": "Composer library to consolidate common site functionality.",
    "type": "project",
    "config": {
        "discard-changes" : true
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.drupal-composer.org"
        }
    ],
    "require": {
        "composer/installers": "^1.2.0",
        "cweagans/composer-patches": "^1.5.0",
        "drupal/core": "8.1.*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"]
        },
        "patches": {
            "drupal/core": {
                "UUID node links": "https://www.drupal.org/files/issues/2353611-uuid-link.67.patch",
                "Menu link deployment": "https://www.drupal.org/files/issues/2577923-menu-link-deploy.40.patch"
            }
        }
    }
}

```
The patches are correctly applied, but drupal/core is installed in the root directory, not web/core.

**Comment by slbmeh** [comment]
You need to configure the installer-paths in the root composer.json.  A package vendor shouldn't have to care about the filesystem you are installing it on, and giving that power to a third party opens up opportunity for malicious acts.  Imagine a package pulled in as a dependency declares it is to be installed at the absolute path `/`... When the package is to be updated, the `rm -rf` will hurt (hopefully not, composer shouldn't be run as root).

**Comment by acbramley** [comment]
@slbmeh fair enough, I've done that for the time being so no worries. Thanks for the response.
