### ISSUE TITLE
[WordPress] Bug in case wp-content folder is moved or renamed

### ISSUE THREAD

**Issue by tomicakorac** [composer/installers#336]
I'd like to use Installers to manage my WP plugins and themes. However in my WP installations `wp-content` directory is renamed to `public` and moved outside of the WP base folder. In this case Installers becomes useless because it installs themes and plugins to a wrong location.

I saw that in `WordPressInsaller.php` plugin and theme paths are hard coded, which is a bad practice. How can we make these paths dynamic, depending on the `wp-config.php` settings related to plugin/theme location?

**Comment by sbuzonas** [comment]
They are not hard coded.  They are mapped to have defaults map to the paths as the application ships.  https://github.com/composer/installers#custom-install-paths
