### ISSUE TITLE
Package not being stored in custom directory

### ISSUE THREAD

**Issue by welly** [composer/installers#347]
Pretty new to using composer/installers so may have missed something but my composer.json looks like:

```
{
    "name": "alastair/tmp",
    "authors": [
        {
            "name": "Alastair Moore",
            "email": "welly@protonmail.com"
        }
    ],
    "require": {
        "composer/installers": "^1.2",
        "dimsemenov/Magnific-Popup": "^1.1"
    },
    "extra": {
        "installer-paths": {
            "libraries/{$name}/": [
                "vendor:dimsemenov"
            ]
        }
    }
}
```

However I'm finding that the package dimsemenov/Magnific-Popup is still landing in the vendors directory. I assume I've missed something, could anyone suggest what?

Thanks,

welly

**Comment by haqqi** [comment]
Similar with my problem. I am using Yii2. At the beginning, when i use this `"vendor/bower/{$name}/": ["vendor:bower-asset"]` it was installed in the correct folder. After recent updates, it is failed to detect the vendor, and installed in the default folder.

**Comment by drupality** [comment]
@haqqi could you tell me which version working ok for you?

**Comment by 0xReki** [comment]
New user here. I can't get it to install at custom paths as well.

**Comment by seanr** [comment]
Same problem with v1.2.0 and I note that the extra portion of the package info doesn't get written to composer.lock.

**Comment by JorisVanEijden** [comment]
I thought I had this issue until I realized the installer-paths are tried in order.
Turned out I had a "conflicting" path a bit above mine. After correcting the order the install location is correct.

**Comment by alcohol** [comment]
Closing due to quiet period. Please re-open if still applicable.
