### ISSUE TITLE
Tag a 1.2.1 release?

### ISSUE THREAD

**Issue by KorvinSzanto** [composer/installers#358]
concrete5 was added to composer/installers back in 2013, but we never really officially supported it. Now with https://github.com/composer/installers/commit/a8aaf0887fc7a85ed8b189326eed7bb7f2a3ff1f we will be able to officially start using composer/installers in distribution.  
The only thing we're waiting on at this point is a tagged release of `composer/installers` so that we can begin recommending people use composer instead of our old distribution methods.

Is there anything holding back a release, if so is there anything I can do to help get a release out sooner than later?

**Comment by artygrand** [comment]
Yes, too many commits since 14 Aug 2016

**Comment by niksamokhvalov** [comment]
v1.3.0 released. Thank you for your input and patience 😉
