### ISSUE TITLE
Composer Keyword Stuffing

### ISSUE THREAD

**Issue by jhabdas** [composer/installers#361]
Please chill with the number of keywords you're including in your package manifest. They're interrupting my debugging workflow and ability to think.

    cat composer.lock

```json
"homepage": "https://composer.github.io/installers/",
"keywords": [
  "Craft",
  "Dolibarr",
  "Eliasis",
  "Hurad",
  "ImageCMS",
  "Kanboard",
  "MODX Evo",
  "Mautic",
  "Maya",
  "OXID",
  "Plentymarkets",
  "Porto",
  "RadPHP",
  "SMF",
  "Thelia",
  "WolfCMS",
  "agl",
  "aimeos",
  "annotatecms",
  "attogram",
  "bitrix",
  "cakephp",
  "chef",
  "cockpit",
  "codeigniter",
  "concrete5",
  "croogo",
  "dokuwiki",
  "drupal",
  "elgg",
  "expressionengine",
  "fuelphp",
  "grav",
  "installer",
  "itop",
  "joomla",
  "kohana",
  "laravel",
  "lavalite",
  "lithium",
  "magento",
  "mako",
  "mediawiki",
  "modulework",
  "moodle",
  "phpbb",
  "piwik",
  "ppi",
  "puppet",
  "reindex",
  "roundcube",
  "shopware",
  "silverstripe",
  "sydes",
  "symfony",
  "typo3",
  "wordpress",
  "yawik",
  "zend",
  "zikula"
]
```

**Comment by sbuzonas** [comment]
It isn't keyword stuffing, those are valid keywords for supported installer types.

**Comment by jhabdas** [comment]
I think you're missing the point of keywords.

**Comment by jhabdas** [comment]
The keywords for this should be something like `custom` and `installer` and that's it. Going beyond that negates the usefulness of keywords. It's stuff like this that caused web crawlers to stop using the keywords meta.

**Comment by sbuzonas** [comment]
It's used by solr on packagist. https://github.com/composer/packagist/blob/master/doc/schema.xml#L274-L281

If the keywords were simply `custom` and `installer` then someone searching for an installer of `expressionengine` packages would likely search `expressionengine installer` and get matches for all installers and need to sort through them. The schema isn't built for web crawlers, the field is intended for use of extra words to have a search hit on that do not exist in the name or description. It has a lower weight than the other fields. Being that none of the installer types are in the package name or description, I believe it is appropriate usage of the keyword field.

**Comment by jhabdas** [comment]
@sbuzonas Thanks for the info. Makes sense. I guess the question is do people really search that way? If so I apologize and this issue was a mistake. But it still seems excessive to list every available installer as a keyword when this seems to be the canonical installer package.
