### ISSUE TITLE
Custom? 

### ISSUE THREAD

**Issue by com2** [composer/installers#372]
I wonder what Custom means in the Readme? Does the table list the supported types? CiviCRM is not  in the table. To me custom would mean that I can do the following to install the extension in a desired Drupal 7 path, however it remains in the vendor path. Please clarify! Thank you.
```
{
    "name" : "org.civicrm.contrib/anonymize",
    "description" : "Anonymize your CiviCRM DB",
    "type" : "civicrm-ext",
    "require": {
        "fzaninotto/faker": "^1.6",
        "symfony/yaml": "^3.2",
        "twig/twig": "~1.0",
        "composer/installers": "~1.0"
    },
    "extra": {
        "installer-paths": {
            "web/sites/default/civiext/{$name}/": ["type:civicrm-ext"]
        }
    }
}
```

**Comment by niksamokhvalov** [comment]
It will no work. You need to create a custom installer, see CONTRIBUTING.md.

**Comment by kenorb** [comment]
Related: <https://github.com/composer/installers/issues/460#issuecomment-740689480>.
