### ISSUE TITLE
"cms", "core", or "mediawiki-core" type?

### ISSUE THREAD

**Issue by davidbarratt** [composer/installers#390]
Would you prefer to add a generic `cms` type (that could be used for `drupal/core` and `mediawiki/core`) or would you prefer to add a `mediawiki-core` type?

or alternatively a `core` type, since both will be installed in a `core` folder within the webroot?

See https://phabricator.wikimedia.org/T190386

**Comment by davidbarratt** [comment]
@niksamokhvalov or @alcohol ?

**Comment by alcohol** [comment]
When it comes to `installers`, I would opt for more specific over generic. Since generic means that once than more than 1 vendor uses it, you can basically almost never change it anymore. So, based on your suggestions, I would go with `mediawiki-core`.

**Comment by davidbarratt** [comment]
Thanks! I opened #391
