### ISSUE TITLE
fontend package installer

### ISSUE THREAD

**Issue by frob** [composer/installers#393]
I have read the issues regarding generic installer and agree that it is problematic to allow generic placement of things. Furthermore, I understand the need to only allow library specific placement of libraries/packages/plugins/modules based on the standards of the library.

However, this leads to a problem for generic frontend libraries (bootstrap as an example). One large benefit of composer for a Drupal site is the ability to put dependencies above the webroot and thus deny access to the outside. However, this means that any frontend libraries either cannot be managed with composer or must be added manually in some other way. 

I propose adding a ```generic-frontend``` type so can install frontend libraries in a separate location from the backend libraries (which already have a place in vendor).

**Comment by rodrigoaguilera** [comment]
Given the popularity of https://asset-packagist.org/ I opened 
https://github.com/composer/installers/issues/394

Maybe the type for the npm and bower assets can change to fit your proposal. 
So now I wonder: Can a package have multiple types?

**Comment by Seldaek** [comment]
IMO this is a bad idea and I don't really want to encourage it. Frontend deps should be installed via npm/yarn, not cobbled up together via Composer. You can use https://packagist.org/packages/oomphinc/composer-installers-extender I guess though..
