### ISSUE TITLE
Add npm-asset and bower-asset types for frontend libraries

### ISSUE THREAD

**Issue by rodrigoaguilera** [composer/installers#394]
There is a very popular composer repo called https://asset-packagist.org/
to install a library from npmjs.org or bower.io.

To be able to install it in custom path a plugin is needed "oomphinc/composer-installers-extender".
I think it will be better if this two types where recognized in this repo as an "official" type.

**Comment by espurnes** [comment]
I agree, it will be useful.

**Comment by phenaproxima** [comment]
+1. This would be very helpful!

**Comment by Seldaek** [comment]
IMO this is a bad idea and I don't really want to encourage it. Frontend deps should be installed via npm/yarn, not cobbled up together via Composer.
