### ISSUE TITLE
[question] coupled with Satis

### ISSUE THREAD

**Issue by illuminate3** [composer/installers#396]
Has anybody seen a package that couples satis with composer/installers?

I am looking to build something like WP which allows you to download modules from an admin panel installed of having to manually install them from composer.

Or if not, any suggestions on who I would go about doing this on my own? I am just not getting who projects like WP and October CMS have done this.

Thanks!

**Comment by Seldaek** [comment]
You can look at https://github.com/contao/contao-manager which is a plugin installer using composer internally.
