### ISSUE TITLE
New type for custom Drupal profiles

### ISSUE THREAD

**Issue by FatGuyLaughing** [composer/installers#398]
We have install types for custom Drupal modules and themes but nothing for profiles. I am requesting a new type of `drupal-custom-profile`.

**Comment by swim** [comment]
Same boat; we have a number of custom profiles on an internal packagist. Updating the composer.json shipped with Drupal core is the only current alternative. Please see https://github.com/composer/installers/pull/416

**Comment by joeparsons** [comment]
Shouldn't this issue be closed since #416 was merged?
