### ISSUE TITLE
Path of dependency's dependencies

### ISSUE THREAD

**Issue by filips123** [composer/installers#411]
Where are dependencies of dependency with custom installation path stored? In `vendor` or custom directory?

For example, I have dependency with package type `framework-plugin`, which should be installed to `plugins/{name}`. Where will it's dependencies be stored? In `vendor` or `plugins/{name}/vendor`?

**Comment by sbuzonas** [comment]
Composer installs all packages under `{vendor-dir}/{vendor}/{package}`, any package installed by `composer/installers` that matches an installation rule would be installed in it's respective directory.

**Comment by filips123** [comment]
For example, I have package with name `example/example-plugin` and type `wordpress-plugin` which should be installed in `wp-content/plugins/example-plugin`. It has some dependencies, for example `monolog/monolog` and others. Where will they (dependencies) be stored? In root `vendor` directory of project or in `wp-content/plugins/example-plugin/vendor`?

**Comment by sbuzonas** [comment]
Yes, they will be installed in the root vendor directory. Because PHP can only declare a class once; all packages, no matter how deep in the dependency tree, are treated as top level dependencies.

**Comment by filips123** [comment]
Thank you!
