### ISSUE TITLE
Downloading only unexisting files

### ISSUE THREAD

**Issue by filips123** [composer/installers#413]
I don't know if this is question for this repository because it is generally about custom composer package type.

Is it possible to set custom composer package type that will only download files that don't exists? So it will not overwrite existing files?

**Comment by sbuzonas** [comment]
It is a question better suited for composer/composer. However, you could do something like that with [custom installers](https://getcomposer.org/doc/articles/custom-installers.md#creating-an-installer).

**Comment by filips123** [comment]
@sbuzonas Is there some detailed guide?

**Comment by Seldaek** [comment]
Closing as this doesn't belong here and anyway not something Composer supports nor will support I believe.
