### ISSUE TITLE
[feature request] Add extra "installer-dir" config to prepend paths destinations

### ISSUE THREAD

**Issue by vever001** [composer/installers#434]
Hello,

Composer supports overriding the vendor location using `vendor-dir`.
There is no equivalent for packages handled by `composer/installers` so everything goes to the folders specified in 'installer-paths`.

I recently made a tiny wrapper here: https://github.com/vever001/composer-installers-dir
Which, as stated, can be useful in many cases like building the project to another directory for a production release.

Would you be open to accept this feature inside `composer/installers`?
If so let me know and I will work on it.

Thank you

**Comment by Seldaek** [comment]
Rather not add even more complexity here sorry, for a deployment script you can run composer install and then move files where they belong IMO.
