### ISSUE TITLE
Auto-Detect Drupal Single Site Install Path

### ISSUE THREAD

**Issue by shama** [composer/installers#44]
Reference #42, #36 and #15. The Drupal types currently require the composer.json to be located in the `sites/all` folder to allow for multi-sites. It appears to be common to want to locate the composer.json in the root of a drupal app. So would be nice for the DrupalInstaller to detect whether it's in root of the app to prefix `sites/all/` to the install path.

@RobLoach has done this in his [DrupalInstaller](https://github.com/RobLoach/composer-installer/blob/master/src/Drupal/ComposerInstaller/DrupalInstaller.php#L36). I think the detection stuff makes sense (and would love a PR or your copy permission Rob) but I would like to get #43 done first.

This would make it so core drupal modules and themes cannot be installed with composer/installers. Which is a good thing but just making it clear.

**Comment by Seldaek** [comment]
Closing here as it is very very old, and I'm assuming another solution was found if there really was something to fix.
