### ISSUE TITLE
Composer 2.0 compatibility

### ISSUE THREAD

**Issue by mbaynton** [composer/installers#447]
All the projects requiring this plugin aren't able to be installed with Composer 2. Updating this plugin to work with Composer 2.0 should remove a roadblock to using those projects and frameworks with Composer 2.

**Comment by danepowell** [comment]
Speaking as the maintainer of BLT and a user of Drupal, I'd really like to see this since it will prevent _any_ user of BLT (and Drupal more generally) from using Composer 2 until it's fixed.

**Comment by mbaynton** [comment]
Fixed by #448

**Comment by Seldaek** [comment]
Note that this isn't released yet, probably will/should do that next week though. But in the meantime if you can try with dev-master version to check all works fine it'd be great.
