### ISSUE TITLE
type: acf-plugin ?

### ISSUE THREAD

**Issue by strarsis** [composer/installers#453]
Would it make sense to add `acf-plugin` as supported package type [as used in this plugin](https://github.com/kevinruscoe/acf-star-rating-field/blob/master/composer.json#L4)?
Map `acf-plugin` to `wordpress-plugin`?

**Comment by Seldaek** [comment]
Well.. is it a wordpress plugin that needs to be installed in the WP plugin dir? If so I think it's fine to declare its type as wordpress-plugin

**Comment by strarsis** [comment]
@Seldaek: Yes, ACF plugins are like normal WordPress plugins, but they hook into ACF (or ACF Pro) and add new functionality (field type, behaviour, etc).

**Comment by Seldaek** [comment]
OK, sounds to me like for composer purposes they should just have the wordpress-plugin type then, it's kind of a detail where they hook after install.
