### ISSUE TITLE
How to store development dependencies in other directories, such as `vendor-dev`?

### ISSUE THREAD

**Issue by allowing** [composer/installers#457]
I want to store development dependencies in the vendor-dev directory. In this way, development dependencies can be ignored and not submitted to the version control system. Although the entire vendor directory is usually ignored, many developers are reluctant to do additional installation work, so they submit the entire vendor to the vcs together.

**Comment by Seldaek** [comment]
We do not advise you to commit the vendor dir https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md - and as such there is no way to split the dev dependencies into another vendor dir.
