### ISSUE TITLE
[feature request] Laminas Framework support

### ISSUE THREAD

**Issue by FabianRahm** [composer/installers#458]
Zend Framework has been replaced by the Laminas MVC framework (https://framework.zend.com/ and https://getlaminas.org/).

We use custom installers and have the type "zend-module" in use. It would be nice to have a "laminas-module" type available with identical functionality.

**Comment by Seldaek** [comment]
Why do you use it/need it? AFAIK this was done initially for BC with old ZF setups. I can't imagine Laminas still requires things to be installed in some specific dir rather than being in vendor like they should be?

**Comment by FabianRahm** [comment]
As per the Laminas Skeleton app (https://github.com/laminas/laminas-mvc-skeleton), Laminas modules are still a thing, residing in /module. When having a unique repo for each module, the ZF2 way to install the module was used: "zend-module".

At this time, I don't use that method any longer.
