### ISSUE TITLE
Missing shopware-platform-plugin for shopware installer, shopware 6.

### ISSUE THREAD

**Issue by radixs** [composer/installers#459]
Hello,
in Shopware 6 the type has been changed to shopware-platform-plugin which is not listed in https://github.com/composer/installers/blob/master/src/Composer/Installers/ShopwareInstaller.php - can this be kindly added?

EDIT:
I think the only thing that needs to be done is extending the array like that:

```
    protected $locations = array(
        'backend-plugin'    => 'engine/Shopware/Plugins/Local/Backend/{$name}/',
        'core-plugin'       => 'engine/Shopware/Plugins/Local/Core/{$name}/',
        'frontend-plugin'   => 'engine/Shopware/Plugins/Local/Frontend/{$name}/',
        'theme'             => 'templates/{$name}/',
        'plugin'            => 'custom/plugins/{$name}/',
        'platform-'plugin'  => 'custom/plugins/{$name}/',
        'frontend-theme'    => 'themes/Frontend/{$name}/',
    );
```

EDIT2:
if someone will be looking in here with the same problem then I have made this: https://packagist.org/packages/radixs/composer-shopware6-installer - use it until composer guys update the installers for Shopware 6.

**Comment by Seldaek** [comment]
I do wonder why this is really needed.. It seems like nobody else is having this problem so maybe your expectations are wrong here, and this is not meant to be like this in shopware 6, but rather those shopware-platform-plugin packages should be in vendor?

Can I get any input from shopware people here? @shyim @pweyck ?

**Comment by radixs** [comment]
> I do wonder why this is really needed.. It seems like nobody else is having this problem so maybe your expectations are wrong here, and this is not meant to be like this in shopware 6, but rather those shopware-platform-plugin packages should be in vendor?
> 
> Can I get any input from shopware people here? @shyim @pweyck ?

Yes, current version of Shopware 6 stores plugins in vendor dir, it was not when I wrote this issue.

**Comment by Seldaek** [comment]
Ok so this can be closed I guess?

**Comment by shyim** [comment]
Yes it's not needed anymore for Shopware 6

**Comment by Seldaek** [comment]
Ok thanks
