### ISSUE TITLE
Composer 2 

### ISSUE THREAD

**Issue by cjdesautels** [composer/installers#468]
Please make this plugin Composer 2 compatible.

**Comment by jacobsaw** [comment]
Have not had an issue until today while attempting to upgrade Drupal core. I've been using Composer 2 since around the end of September.

Only happens when running `update --with-all-dependencies`.

````
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - composer/installers[v1.7.0, ..., v1.8.0] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires composer/installers ^1.2 -> satisfiable by composer/installers[v1.7.0, v1.8.0].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
````

**Comment by markfullmer** [comment]
Based on the commit https://github.com/composer/installers/commit/d2a98321ab66945396ef147387f93eee4c05089f#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34, and the release notes in https://github.com/composer/installers/releases/tag/v1.9.0, the `1.9.0` release of this package is Composer 2.0 compatible.

The output shown in the comment above (`composer/installers[v1.7.0, ..., v1.8.0]`) suggests that the reporter has a specific `^1` version requirement (I got the same issue with an explicit requirement of `"composer/installers": "1.7.0"`.

Therefore, the appropriate resolution should be to update requirement dependencies; this issue likely can be closed.

**Comment by jacobsaw** [comment]
Composer.json:
`"composer/installers": "^1.2"`

Composer.lock:
````
"name": "composer/installers",
"version": "v1.9.0",
````

**Comment by markfullmer** [comment]
@jacobsaw , try: `composer update drupal/core 'drupal/core-* composer/*' --with-all-dependencies`

(I still maintain this is an issue with version/dependencies, rather than Composer 2 compatibility in this package).

**Comment by jacobsaw** [comment]
@markfullmer - Thanks, that does return no errors!
