### ISSUE TITLE
Remove TYPO3 again

### ISSUE THREAD

**Issue by gilbertsoft** [composer/installers#470]
In August 2013 TYPO3 was [added](https://github.com/composer/installers/commit/56a0ad4f496708e0c08664807523de0fd44effba#diff-ae512e31f9fdd4aaa11bc220cbd9f4de45e137af8a7c22347d2ed204dda317fe) to `composer/installers` here as a first step for TYPO3's Composer support. However, as this was never sufficient for TYPO3 and never worked properly, the TYPO3 Core-Dev Team wrote its own installer and in February 2014 the first version was [released](https://github.com/TYPO3/CmsComposerInstallers/releases/tag/1.0.0). The two plug-ins, however, naturally clashed, and as more and more problems arose, a [conflict was introduced](https://github.com/TYPO3/CmsComposerInstallers/commit/f33ee73c12596b1f2bd714c9f69f451a18b4d79d) on the TYPO3 side in November 2015. But as this caused new problems with packages relying on `composer/installers`, TYPO3 was [removed again](https://github.com/composer/installers/pull/281) from `composer/installers` in January 2016.

As a result, a user complained and added TYPO3 again. But now we had a version of `composer/installers` without TYPO3 and we were able to [relax our conflict definition](https://github.com/TYPO3/CmsComposerInstallers/commit/ce7faaeb9226e8643285f0422fc96f9bcec3b13e) a bit. Now it was possible to use our installer together with `composer/installers` and everyone was happy again.

Then came the release of Composer 2 a month ago and since there is no version compatible to v2 without TYPO3, the problem arised again. E.g. [Aimeos](https://aimeos.org/typo3-shop-extension) and TYPO3 can't be installed with Composer 2 and Aimeos has [opened an issue with us](https://github.com/TYPO3/CmsComposerInstallers/issues/108) which we are not able to solve in our installer.

We currently see the following solutions:

1. [Remove TYPO3](https://github.com/composer/installers/pull/469) from `composer/installers`. Back in 2016 we were criticized that there was not enough time for a migration to TYPO3's installer. Now over 4 years have passed and this argument is or should be invalidated. But as we noticed back then, this is actually a breaking change and so you should actually publish a v2 of `composer/installers` after removing TYPO3 again, which is not very nice.
2. Introducing an event during the initialization of the installers as prepared in [my PR](https://github.com/composer/installers/pull/466). This would allow us to switch off the installer here for TYPO3 in our installer. Up to now, this has only been possible if our users deactivate the installer in their root composer.json via `extra.installer-disable`, which is an unreasonable demand and very error-prone. That's why I created this draft, which would allow disabling installers from within plugins. You have to tell me if this is desired from your side at all or maybe this contradicts your concept here.
3. Aimeos creates its own installer, either generally for all projects, they support not only TYPO3, or with a special installer for TYPO3 only.

In the opinion of the TYPO3 Core-Dev Team solution 1 would be the cleanest and the right one but we are open for a discussion here.

References:

- #96
- #281 
- #300
- #466 
- #469

CC:

- @bmack
- @naderman
- @EmiiKhaos
- @aimeos
- @mbrodala

**Comment by aimeos** [comment]
Maybe it's time to release a composer/installers 2.0 version similar to composer 2.0 where old/conflicting code like this can be removed safely.

**Comment by gilbertsoft** [comment]
Just found this hint here https://github.com/composer/installers/pull/49#issuecomment-12556499. So finally each package should provide an own installer plugin anyway.

**Comment by naderman** [comment]
As an outsider to this, what I don't quite understand is:
- In how far do the two installers differ exactly? Why do they both advertise to work for the same package types?
- Would a solution be for the installer that was published later to support different package types? And packages which want to use the typo3 installer to use different types?
- Why can't Aimeos be installed with Composer v2?
- Why is disabling an installer you don't want to use in extra "unreasonable" and "error prone"?
- I don't understand what you mean exactly with solution number 3?

**Comment by gilbertsoft** [comment]
> 
> 
> As an outsider to this, what I don't quite understand is:
> 
>     * In how far do the two installers differ exactly? Why do they both advertise to work for the same package types?

One important thing here is the core developemnt of TYPO3 which is done in a monolithic repository. Later we create the split packages for the composer support. So your installer supports two modes, one for the core development and one for the usage of the split packages. And yes, they both advertise to work with the same package type, but the one provided here does not take care about the core development workflows and so can not be used. The reason is simple as mentioned before, the implementation here was the first try for TYPO3's composer support which later was replaced by our own installer plugin.

> 
>     * Would a solution be for the installer that was published later to support different package types? And packages which want to use the typo3 installer to use different types?

I already thought about this too but it does not look this is really a solution. This would end in the 2300 published packages at packagist must change their type see https://packagist.org/explore/?type=typo3-cms-extension.

> 
>     * Why can't Aimeos be installed with Composer v2?

Aimeos can be installed with Composer 2 standalone (Symfony, Laravel, etc.) but not the Aimeos TYPO3 Extension because v1.9 here is conflicting our installer and so no version with plugin api version 2 of composer is available.

>     * Why is disabling an installer you don't want to use in extra "unreasonable" and "error prone"?

This has to be added to every TYPO3 project, if one forgets to do so it will endup with errors. Many of our users are still new to composer and that's a new hurdle for them to overcome.

>     * I don't understand what you mean exactly with solution number 3?

As the composer/installers was meant as a [temporary workaround](https://github.com/composer/installers/pull/49#issuecomment-12556499) and each package better provide its own installer plugin it would also be possible that Aimeos uses its own installer plugin here without relying to composer/installers.

**Comment by naderman** [comment]
> Aimeos can be installed with Composer 2 standalone (Symfony, Laravel, etc.) but not the Aimeos TYPO3 Extension because v1.9 here is conflicting our installer and so no version with plugin api version 2 of composer is available.

I don't understand this sentence. Do you mean Aimeos Typo3 extension requires 1.9 of composer/installers? Why?

> As the composer/installers was meant as a temporary workaround and each package better provide its own installer plugin it would also be possible that Aimeos uses its own installer plugin here without relying to composer/installers.

I think you misunderstood that comment you quoted. The goal would be for projects to use Composer's own functionality only, so that composer/installers are not needed. At worst a plugin for only specific additional functionality may be provided, e.g. to make db changes, but moving files to non-standard directories not be necessary if a project properly implements composer and works by placing packages into the vendor directory.

**Comment by aimeos** [comment]
@naderman Here's a more detailed explanation for your 3rd point:
Aimeos is at it's core a PHP e-commerce library and there can be extension of type "aimeos-extension" to add new functionality. For this, composer/installers is used and this works fine when Aimeos is used as part of a Laravel, Symfony or other PHP frameworks (which use composer/installers themselves).
When used with TYPO3, the TYPO3 core has a hard restriction to composer/installers:1.0.24, the last version which doesn't contain an installer for TYPO3 extensions. This was OK up to now but with the release of composer 2.0, composer/installers:1.9 is required due to changes in the composer plugin API. Now, composer 2.0 complains about the composer/installers:1.0.24 required by TYPO3, which doesn't support the new plugin API.
The reason why TYPO3 restricts composer/installers to 1.0.24 was that it's shipped with a custom (non composer/installers based) installer and conflicts with new composer/installers versions because they would both care about the same extensions (type typo3-extension).

**Comment by aimeos** [comment]
> I think you misunderstood that comment you quoted. The goal would be for projects to use Composer's own functionality only, so that composer/installers are not needed. At worst a plugin for only specific additional functionality may be provided, e.g. to make db changes, but moving files to non-standard directories not be necessary if a project properly implements composer and works by placing packages into the vendor directory.

The reason why Aimeos uses composer/installers is that it wasn't (isn't?) possible to discover Aimeos extensions in the vendor directory automatically. Has this changed in the meantime?

**Comment by gilbertsoft** [comment]
> 
> The reason why Aimeos uses composer/installers is that it wasn't (isn't?) possible to discover Aimeos extensions in the vendor directory automatically. Has this changed in the meantime?

I guess this should be possible by iterate through all packages and check for a specific type, `aimeos-extension` in this case. Question is here, do you have to support other non composer installs except TYPO3 non composer installations?

**Comment by aimeos** [comment]
Good point. That may be possible even if we don't like non-composer installations because they are hard to support and update.

**Comment by gilbertsoft** [comment]
> I think you misunderstood that comment you quoted. The goal would be for projects to use Composer's own functionality only, so that composer/installers are not needed. At worst a plugin for only specific additional functionality may be provided, e.g. to make db changes, but moving files to non-standard directories not be necessary if a project properly implements composer and works by placing packages into the vendor directory.

In the case of TYPO3 Extensions we have a folder `Resources/Public` which must be exposed to the web root `typo3conf/ext/[extension key]/Resources/Public`. Here there is still work in progress from the core side to support also other install locations like the vendor folder for extensions. But currently this is not possible because the core always looks into `typo3conf/ext` for extensions. That's the case since the beginning of TYPO3 and not possible to quickly change. In the last 8 years we are working hard on the refactoring of the core and this is also one point.
Compared to Symfony if I recall correctly they use Flex to achieve such requirements like publishing assets etc. In the end when our refactoring is done we will probably have similar solution here. And that's also a reason we use our own installer plugin to be able to react fastly on core changes here. `typo3/cms-composer-installers` is developed independent from the core in it's own Github repo, this makes it possible to make independent releases here and quickly provide fixes if needed.

**Comment by Seldaek** [comment]
Just to be entirely clear here.. if we released a 2.0 version of this plugin without Typo3 support, would it work out for everyone? I guess old TYPO3 setups which absolutely rely on this can still stick to the 1.x release that works for them, and new/old-but-supported TYPO3 setup could then upgrade to composer 2 + https://github.com/TYPO3/CmsComposerInstallers + composer/installers 2.0 if they need it for something else like Aimeos packages.

Is that correct? 

As a sidenote, @aimeos would it help if [InstalledVersions](https://getcomposer.org/doc/07-runtime.md#installed-versions) offered also a way to find packages by type, and possibly find their install dir? Would that allow you to register plugins correctly without requiring plugin packages to be in a special dir to find them? Would you need any other info in there?

**Comment by aimeos** [comment]
@Seldaek Yes, that would be very helpful for us and also for many other packages having the same needs for auto-discovery. An associative list of package name and installation directory would be enough but for maximum extensibility, you can also offer a list of package name/data object pairs.

@gilbertsoft Can you answer the TYPO3 question?

**Comment by gilbertsoft** [comment]
@Seldaek Yes, absolutely correct.

The only user I know who has complained back then (EmiiKhaos) and which was also mentioned by me in the introduction did not leave a comment here.

**Comment by helhum** [comment]
@Seldaek Yes, a 2.0 release of composer/installers without TYPO3 support would be a great solution for us. 

And a runtime API to access install paths along with versions of packages (including the root package), would also solve a bunch of issues for TYPO3 as well.

It would almost completely remove the need for our Composer plugin.

**Comment by Seldaek** [comment]
@helhum @aimeos I created https://github.com/composer/composer/issues/9648 to track the improvements in Composer itself.

**Comment by helhum** [comment]
> I created [composer/composer#9648](https://github.com/composer/composer/issues/9648) to track the improvements in Composer itself.

awesome! Thanks a bunch (again)!

**Comment by jonaseberle** [comment]
+1 for a v2 release with removed TYPO3. 
Currently that blocks projects with other packages requiring `composer/installers` from using composer v2.

**Comment by Seldaek** [comment]
Ok this is done finally.. I am also planning to require PHP 7.2 for v2 of composer/installers.. Would that be a problem for anyone here?

**Comment by Seldaek** [comment]
https://github.com/composer/installers/releases/tag/v2.0.0-alpha1 is now available for testing. Please someone test this and confirm things are good? :) I'd aim to make it a final release in a week or two depending on feedback.

**Comment by gilbertsoft** [comment]
@Seldaek tested with my PR https://github.com/TYPO3/CmsComposerInstallers/pull/122 and works fine like expected. As you know Aimeos doesn't use composer/installers anymore so this case is solved anyway. Thanks for your support here!
