### ISSUE TITLE
Review list of installers and which one are still needed

### ISSUE THREAD

**Issue by Seldaek** [composer/installers#477]
If we do a 2.0 release, we should make sure any installers which are not needed anymore get cleaned up. This will require a community effort though as we have no clue about most of the projects having custom installers here.

If you know of one which needs breaking changes or could be removed as it's unnecessary, please say so here. You can find the [complete list in the README](https://github.com/composer/installers/blob/main/README.md#current-supported-package-types).

Already known/planned to be removed are:

- [Pimcore](https://github.com/composer/installers/issues/471)
- [TYPO3](https://github.com/composer/installers/issues/470)

Also noteworthy to most people reading this is that we are looking to improve even further the data available at runtime for users of Composer 2 (or 2.1+ in this case), which probably should help the use case of applications registering extensions dynamically at runtime: https://github.com/composer/composer/issues/9648

**Comment by greg-1-anderson** [comment]
Drupal should be removed or updated. I didn't make an issue on drupal.org yet, but I [started a discussion in Slack](https://drupal.slack.com/archives/C392CHBEW/p1611676057039500).

**Comment by brandonkelly** [comment]
[CraftInstaller](https://github.com/composer/installers/blob/main/src/Composer/Installers/CraftInstaller.php) is safe to remove. That hasn’t been needed since Craft 3.0.

**Comment by Cheddam** [comment]
[SilverStripeInstaller](https://github.com/composer/installers/blob/main/src/Composer/Installers/SilverStripeInstaller.php) is definitely still required, particularly for themes.

**Comment by marc1706** [comment]
[PhpBBInstaller](https://github.com/composer/installers/blob/main/src/Composer/Installers/PhpBBInstaller.php) is still needed

**Comment by Tobion** [comment]
Symfony1 can probably be removed by now

**Comment by mbabker** [comment]
You can most likely drop [JoomlaInstaller](https://github.com/composer/installers/blob/main/src/Composer/Installers/JoomlaInstaller.php), the app itself isn't distributed in a Composer-supported manner and there is a [community plugin](https://github.com/joomlatools/joomlatools-composer) which does more to install extensions into Joomla in the way the application requires them added.

**Comment by nickveenhof** [comment]
I wouldn't remove the Drupal one, many projects still depend on that and it would break massively imho? Unless there is a drupal composer plugin, but this doesn't seem to be official according to this search: https://github.com/drupal?q=composer&type=&language=&sort=

**Comment by GaryJones** [comment]
The WordPress ones are still needed.

**Comment by lukasbestle** [comment]
Kirby is also planned to be removed: https://github.com/composer/installers/pull/485

**Comment by Seldaek** [comment]
Ok now removed for the upcoming 2.0:

- Symfony1
- Joomla
- Pimcore
- Craft
- TYPO3 CMS
- Kirby

We still have a long list of supported platforms, of which I assume many are dead and buried by now, but I don't really have time to go through each one by one so I guess we'll leave it at that.

**Comment by Seldaek** [comment]
https://github.com/composer/installers/releases/tag/v2.0.0-alpha1 is now available for testing. Please someone test this and confirm things are good? :) I'd aim to make it a final release in a week or two depending on feedback.

**Comment by aimeos** [comment]
You can also remove installer for Aimeos as we use the composer InstalledVersions::getPackageByType() method now.

**Comment by Seldaek** [comment]
@aimeos thanks - done in https://github.com/composer/installers/commit/0a9a8dd9a3eb0387d2961bfffd77842dd4fdd08f
