### ISSUE TITLE
public key signature for installer

### ISSUE THREAD

**Issue by tvannahl** [composer/installers#483]
Hello,

I'm searching for a way to validate the authenticity of the composer installer. I did find a page referencing [public keys](https://composer.github.io/pubkeys.html) for snapshots and tags but I did not manage to find a real signature file related to either `composer-install.php` nor `composer.phar`.

Unfortunately https://composer.github.io/installer.sig does not contain a signature but only a hash value of `composer-install.php`.

Maybe this is something I missed?

**Comment by Seldaek** [comment]
There are no signatures no only the checksum.
