### ISSUE TITLE
CakePHPInstaller with composer 2 and parallel install problem

### ISSUE THREAD

**Issue by Erwane** [composer/installers#488]
my composer.json test file 
```json
{
  "name": "me/project",
  "description": "description",
  "minimum-stability": "stable",
  "license": "proprietary",
  "require": {
    "erwane/cakephp-hcaptcha": "^1.0",
    "composer/installers": "^1.0"
  }
}
```
At first `composer install` a `Plugin` dir is created, plugin is not in PSR-4 path and can't be loaded.

At this point, another `composer install` will re-extract requirements into vendor dir.

After debugging, this is due to Cake version check.
Parallel install in composer 2 don't return `cakephp/cakephp` as installed at first run, because he's not, it's "in progress".

I don't found where is a "should be installed or is installed" packages list.
The new `InstalledVersions::getInstalledPackages()` is not filled at first install.

Here, some debugs of **first** composer install
```
Package operations: 17 installs, 0 updates, 0 removals
  - Installing composer/installers (dev-main): Symlinking from /home/erwane/projects/tests/composer-installers
  - Installing cakephp/chronos (2.1.2): Extracting archive
  - Installing composer/ca-bundle (1.2.9): Extracting archive
  - Installing psr/simple-cache (1.0.1): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-server-handler (1.0.1): Extracting archive
  - Installing psr/http-server-middleware (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing psr/container (2.0.1): Extracting archive
  - Installing league/container (3.3.5): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing laminas/laminas-zendframework-bridge (1.2.0): Extracting archive
  - Installing laminas/laminas-diactoros (2.5.1): Extracting archive
  - Installing laminas/laminas-httphandlerrunner (1.4.0): Extracting archive
  - Installing cakephp/cakephp (4.2.6): Extracting archive
Composer\Installers\CakePHPInstaller::matchesCakeVersionArray
(
    [0] => composer/ca-bundle
    [1] => composer/composer
    [2] => composer/installers
    [3] => composer/metadata-minifier
    [4] => composer/semver
    [5] => composer/spdx-licenses
    [6] => composer/xdebug-handler
    [7] => justinrainbow/json-schema
    [8] => phpstan/phpstan
    [9] => phpstan/phpstan-phpunit
    [10] => psr/log
    [11] => react/promise
    [12] => roundcube/plugin-installer
    [13] => seld/jsonlint
    [14] => seld/phar-utils
    [15] => shama/baton
    [16] => symfony/console
    [17] => symfony/debug
    [18] => symfony/filesystem
    [19] => symfony/finder
    [20] => symfony/phpunit-bridge
    [21] => symfony/polyfill-ctype
    [22] => symfony/polyfill-mbstring
    [23] => symfony/process
    [24] => me/project
)
```
At first `CakePHPInstaller::getLocations()` call, there is no `cakephp/cakephp` plugin installed.

One possible resolution is to return `true` if cakephp/cakephp is not found, then the plugin is installed in the standard vendor dir.

This is only for cakephp2, maybe cakephp 2 composer.json should require composer-api-plugin version 1 to be sure to install plugins in right place ?

**Comment by Seldaek** [comment]
Has this been resolved somehow?

**Comment by Erwane** [comment]
Only by using composer version 1.
I'm not sure there is a solution for this with composer 2. And i'm not sure this is still used :/

**Comment by Seldaek** [comment]
Ok yeah I think I can reproduce, so the problem is on first install it installs in `Plugin/{$name}/`, but then once cakephp is installed it sees cakephp >3 is present and then it switches to installing in `vendor/{$vendor}/{$name}` (which is the default target really, making the plugin useless.

I guess the solution if you have some misbehaving plugin that is still requiring this even tho it shouldn't, is to add this to your composer.json:

```
{
    "extra": {
        "installer-disable": [
            "cakephp"
        ]
    }
}
```

That will make sure the cakephp installer isn't used, as it doesn't seem to be needed.
