### ISSUE TITLE
How to apply for specific root-package only?

### ISSUE THREAD

**Issue by mvorisek** [composer/installers#499]
`locations` like https://github.com/composer/installers/blob/main/src/Composer/Installers/PrestashopInstaller.php#L8 should apply when the main project is some specific project like `prestashop/prestashop` here.

How to update the `src/Composer/Installers/PrestashopInstaller.php` file to achive that?

**Comment by Seldaek** [comment]
I'm not sure I understand what you are saying.. Is there a case for installing prestashop modules/themes outside of the context of a prestashop project?

**Comment by mvorisek** [comment]
Yes, when I include prestashop/prestashop package as a dependency in another/root package, the `locations` should be not honored, as using them in the new another/root package is wrong.

**Comment by Seldaek** [comment]
Well, I think disabling the custom installer then like you did as per the other issue is probably the best fix. I don't think the use case is broad enough and I don't think it's usually possible to determine if we are in a prestashop project or not anyway.
