### ISSUE TITLE
composer 2.3.5 breaks composer/installers

### ISSUE THREAD

**Issue by aaronredwood** [composer/installers#508]
I use composer/installers as part of our roots/bedrock based WordPress multisite codebase. As part of a recent system update, we upgraded composer to version 2.3.5. After running normal deployment process, site was broken. Determined cause to be that WordPress theme and plugins had not been installed to custom locations, just installed into vendor folder. Downgrading to composer 2.1.3 fixed problem. We were running 2.1.3 locally, so that's why we tried that version; did not spend any time trying to identify specific version where defect occurs. Version of composer/installers in production is 1.12.

**Comment by Seldaek** [comment]
Can you check if composer/installers 2.1.1 works? And if not, it'd be nice if you could try variuos composer versions to see which broke. Try `composer self-update 2.2.12` vs  `composer self-update --stable` for example to see if 2.3.0 broke it or if 2.2.x was already broken?

**Comment by fredpotvin-platformsh** [comment]
@aaronredwood upgrade to 2.3.6. The allow plugin directive is enforced now but 2.3.6 will simply continue without executing your plugins, so, `composer/installers` won't run. It was fixed by https://github.com/composer/composer/pull/10920 which is included in 2.3.6
