### ISSUE TITLE
Support https://asset-packagist.org/ types?

### ISSUE THREAD

**Issue by back-2-95** [composer/installers#513]
Could types from https://asset-packagist.org/ be added to composer/installers:

["type:bower-asset", "type:npm-asset"]

Currently `oomphinc/composer-installers-extender` plugin is needed for using those.

**Comment by back-2-95** [comment]
More information is here https://asset-packagist.org/site/about

**Comment by Seldaek** [comment]
Sorry but I'd rather not do this as I don't want to promote what I view as a bad practice. People should rather use npm to install npm packages IMO.

**Comment by back-2-95** [comment]
I understand 👍 

We also use this only for Drupal which loads libraries used by modules and which must go to a certain directory.
