### ISSUE TITLE
Add a installer for Laminas project

### ISSUE THREAD

**Issue by derpixler** [composer/installers#517]
There currently so many custom installers for different types of frameworks but [Laminas](https://getlaminas.org/) is missing.

Laminas will normally install a "Module" into the root of an Laminas Application into `module/`.

In some Laminas module package you can use "type": "laminas-module"

**Comment by Seldaek** [comment]
Is this really required? It seems to me like Laminas should be more modern than this, and if it's needed Id' like to hear it from someone on the Laminas team. In the meantime closing this as it is very old.
