### ISSUE TITLE
Composer Install Installs Modules in "vendor" Instead of Specified "modules" Directory

### ISSUE THREAD

**Issue by luizkim** [composer/installers#532]
I'm encountering an issue where running composer install installs the modules specified in the installer-paths configuration in the "vendor" directory instead of the specified "modules" directory.

Steps to Reproduce:

Clone the repository.
Run composer install.
Check the installed modules' location.
Expected Behavior:
Modules should be installed in the "modules" directory as specified in the installer-paths configuration.

Actual Behavior:
Modules are being installed in the "vendor" directory instead of the specified "modules" directory.

My Composer.json:
https://github.com/ControleOnline/api-community/blob/production/composer.json

**Comment by Seldaek** [comment]
These are symfony bundles, so I think you'd need to require https://github.com/oomphinc/composer-installers-extender to allow overriding their install paths. This package won't do it as it is not required for symfony bundles.
