### ISSUE TITLE
Add extra to disable installers

### ISSUE THREAD

**Issue by shama** [composer/installers#67]
Setting this extra would disable installers and install to the native `vendor` dir. Useful for users who have configured their framework to consume packages from the default dir (but the framework has not officially supported it).

Reference this topic: https://groups.google.com/forum/?fromgroups=#!topic/composer-dev/9JtvlkQ1DNE

Maybe `installer-disable`?

**Comment by slbmeh** [comment]
I use WordPress and Moodle in a project. I want to implement my own WordPress installer but leave the Moodle behavior as is. I think if there is an implementation for this, it should expose the functionality in the public api so other installers can leverage this. #211 is one of these particular scenarios.
