### ISSUE TITLE
Missing Frameworks

### ISSUE THREAD

**Issue by shama** [composer/installers#8]
More PHP frameworks that should be included (in no particular order):
- ~~[Magento](http://www.magentocommerce.com/)~~  29a5ba91a8d7cf8ce6743ae4bb89f09a2f7be9cc
- ~~[Yii](http://www.yiiframework.com/)~~ 85e44424e7c64421904806b06a36244e52cd90f6
- ~~[Solar/Aura](http://auraphp.github.com/)~~ See #24
- [Zikula](http://zikula.org/)
- ~~[PPI](http://www.ppi.io/)~~  c50ae51d3c938b261c542289a13db2611e91d69a
- [Agavi](http://www.agavi.org/)
- [Chisimba](http://www.chisimba.com/)
- [ezPublish](http://ez.no/Community)
- [Phorum](http://www.phorum.org/docs/html/)
- [MicroMVC](http://micromvc.com/)
- ~~[Kohana](http://kohanaframework.org/)~~ 59bb85073c92d77c07112188726546e3958d16d0
- ~~[TYPO3](http://typo3.org/)~~ a02480ae3785e88e26527d21abe50c31fe2edd7d
- ~~[FLOW3](http://flow3.typo3.org/)~~

**Comment by christhomas** [comment]
you should also allow a "generic" type which allows me to add a library which just clones to a folder of my choosing and does nothing special to it.

**Comment by shama** [comment]
@christhomas That generic type exists and is `library` which can be configured through the `vendor-dir` option. Or if you need further control you could write a custom installer.

**Comment by vmwinckler** [comment]
[Slim](http://www.slimframework.com/) ?

**Comment by sbuzonas** [comment]
> [Slim](http://www.slimframework.com/) ?

Isn't Slim composer native?

**Comment by Seldaek** [comment]
Closing as I think we got a decent coverage now ;)
